version: '3.4'

services:
  admin-auth-service:
   image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/admin-auth-service
   environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: admin-auth-service

  admin-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/admin-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: admin-service

  book-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/book-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: book-service

  comment-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/comment-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: comment-service

  copy-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/copy-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: copy-service

  email-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/email-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: email-service

  eureka-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/eureka-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: eureka-service

  gateway-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/gateway-service
    ports: 
      - 8080:8080
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: gateway-service

  order-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/order-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: order-service

  user-auth-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/user-auth-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: user-auth-service

  user-service:
    image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/user-service
    environment: 
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: skywalking-oap-server:11800
      SW_AGENT_NAME: user-service

  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper