version: '3.4'

services:
  perfectlyfinelibraryfrontend:
    image: perfectlyfinelibraryfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 80:80
    environment: 
      - NGINX_PORT=80
