---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: swr.cn-north-4.myhuaweicloud.com/fdse21group25/frontend
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32677
  selector:
   app: frontend



---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 32688
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka  
  replicas: 2
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-eureka-service-sw-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 60
            successThreshold: 1



---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 2
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-gateway-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-auth-service
spec:
  selector:
    matchLabels:
      app: admin-auth-service
  replicas: 1
  template:
    metadata:
      name: admin-auth-service
      labels:
        app: admin-auth-service
    spec:
      containers:
        - name: admin-auth-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-admin-auth-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  selector:
    matchLabels:
      app: admin-service
  replicas: 1
  template:
    metadata:
      name: admin-service
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-admin-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  selector:
    matchLabels:
      app: book-service
  replicas: 1
  template:
    metadata:
      name: book-service
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-book-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-service
spec:
  selector:
    matchLabels:
      app: copy-service
  replicas: 1
  template:
    metadata:
      name: copy-service
      labels:
        app: copy-service
    spec:
      containers:
        - name: copy-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-copy-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 1
  template:
    metadata:
      name: email-service
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-email-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-order-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
spec:
  selector:
    matchLabels:
      app: user-auth-service
  replicas: 1
  template:
    metadata:
      name: user-auth-service
      labels:
        app: user-auth-service
    spec:
      containers:
        - name: user-auth-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-user-auth-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-user-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  selector:
    matchLabels:
      app: comment-service
  replicas: 1
  template:
    metadata:
      name: comment-service
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: registry.cn-hangzhou.aliyuncs.com/softlab/liu-comment-service-sw:v1
          env:
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "collector.trace.svc.cluster.local:3200"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1